### ISSUE TITLE
[Testbug] Body read failed failure on Linux

### ISSUE THREAD

**Issue by staticlibs** [wargio/naxsi#45]
After python tests conversion there is an intermittent failure observed on Linux:

```
======================================================================
ERROR: test_26 (test_00naxsi_base.naxsi_base)
TEST 26: Testing MULTIPART POSTs (BAD CONTENT LEN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/naxsi/naxsi/unit-tests/python/test_00naxsi_base.py", line 804, in test_26
    ec = nr.request(
  File "/home/runner/work/naxsi/naxsi/unit-tests/python/_test_utils.py", line 289, in request
    status, _, body = send_request(self.port, url, method, headers, data)
  File "/home/runner/work/naxsi/naxsi/unit-tests/python/_test_utils.py", line 210, in send_request
    return send_raw_request(port, req_bytes)
  File "/home/runner/work/naxsi/naxsi/unit-tests/python/_test_utils.py", line 218, in send_raw_request
    status, headers, body = read_response(sock)
  File "/home/runner/work/naxsi/naxsi/unit-tests/python/_test_utils.py", line 186, in read_response
    raise NaxsiTestException("Body read failed, read: [{}]".format(buf[:write_pos]))
_test_utils.NaxsiTestException: Body read failed, read: [bytearray(b'HTTP/1.1 412 Precondition Failed\r\nServer: nginx/1.16.1\r\nDate: Wed, 02 Nov 2022 20:54:57 GMT\r\nContent-Type: text/html\r\nContent-Length: 173\r\nConnection: keep-alive\r\n\r\n<html>\r\n<head><title>412 Precondition Failed</title></head>\r\n<body>\r\n<center><h1>412 Precondition Failed</h1></center>\r\n<hr><center>nginx/1.16.1</center>\r\n</body>\r\n</html>\r\nHTTP/1.1 400 Bad Request\r\nServer: nginx/1.16.1\r\nDate: Wed, 02 Nov 2022 20:54:57 GMT\r\nContent-Type: text/html\r\nContent-Length: 157\r\nConnection: close\r\n\r\n<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx/1.16.1</center>\r\n</body>\r\n</html>\r\n')]

----------------------------------------------------------------------
```

I've never seen it in local Linux runs, but apparently it happens sometimes on CI. Root cause is currently not clear (possibly off-by-1 error in body read code in test HTTP client), intend to investigate it to have clean test runs. The problem is highly unlikely to be related to any real problem with Naxsi/Nginx.

**Comment by staticlibs** [comment]
Expected response read calculation in test HTTP client was incorrect, it was trying to read more data from socket than were advertised by server (in headers length + content length). Will submit a PR to fix this shortly.
